import { z } from "zod";
import { SpecVersionSchema, IsoDateTimeSchema } from "../common/primitives.js";

/**
 * Strict runtime Zod schema for VoiceIntent kind.
 * Represents the four voice intent categories specified in the System Design.
 */
export const VoiceIntentKindSchema = z.enum([
  "thank_gift",
  "welcome_follow",
  "game_commentary",
  "system",
]);

export type VoiceIntentKind = z.infer<typeof VoiceIntentKindSchema>;

/**
 * Strict runtime Zod schema for VoiceIntent variables container.
 * Requires a plain object container (Object.prototype or null prototype)
 * mapping string keys strictly to string or finite number scalar values.
 * Uses Reflect.get for assertion-free property inspection.
 */
export const VoiceIntentVariablesSchema = z.custom<Record<string, string | number>>(
  (val) => {
    if (typeof val !== "object" || val === null || Array.isArray(val)) {
      return false;
    }
    const proto = Object.getPrototypeOf(val);
    if (proto !== Object.prototype && proto !== null) {
      return false;
    }
    for (const key of Reflect.ownKeys(val)) {
      if (typeof key !== "string") return false;
      const v = Reflect.get(val, key);
      if (typeof v === "string") continue;
      if (typeof v === "number" && Number.isFinite(v)) continue;
      return false;
    }
    return true;
  },
  "Variables must be a plain object mapping string keys to string or finite number values"
);

export type VoiceIntentVariables = z.infer<typeof VoiceIntentVariablesSchema>;

/**
 * Strict runtime Zod schema for VoiceIntent.
 * Versioned contract for voice reaction intents generated by the Voice Reaction Engine.
 */
export const VoiceIntentSchema = z
  .object({
    specVersion: SpecVersionSchema,
    intentId: z.string().min(1),
    eventId: z.string().min(1).nullable(),
    kind: VoiceIntentKindSchema,
    priority: z.number().int(),
    templateGroup: z.string().min(1),
    variables: VoiceIntentVariablesSchema,
    voiceProfileId: z.string().min(1),
    dedupeKey: z.string().min(1).nullable(),
    expiresAt: IsoDateTimeSchema,
  })
  .strict();

export type VoiceIntent = z.infer<typeof VoiceIntentSchema>;

/**
 * Strict runtime Zod schema for Voice interrupt policy.
 * Controls whether and how new voice clips interrupt currently playing audio.
 */
export const VoiceInterruptPolicySchema = z.enum([
  "never_interrupt",
  "interrupt_lower_priority",
  "interrupt_any",
]);

export type VoiceInterruptPolicy = z.infer<typeof VoiceInterruptPolicySchema>;
